version: '3'
services:
  app:
    image: golang:1.22
    container_name: server
    ports:
      - '8085:8000'
    volumes:
      - type: bind
        source: ./src
        target: /go/src
    tty: true
